name: Flutter Web Deployment

on:
  release:
    types: [published]

jobs:
  # test:
  #   name: Build and release
  #   runs-on: ubuntu-20.04

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Java
  #       uses: actions/setup-java@v2
  #       with:
  #         distribution: 'zulu'
  #         java-version: "12.x"

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v1
  #       with:
  #         channel: stable

  #     - name: Flutter version
  #       run: flutter --version

  #     - name: Cache pub dependencies
  #       uses: actions/cache@v2
  #       with:
  #         path: ${{ env.FLUTTER_HOME }}/.pub-cache
  #         key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
  #         restore-keys: ${{ runner.os }}-pub-

  #     - name: Clean flutter
  #       run: flutter clean

  #     - name: Import pub dependencies
  #       run: flutter pub get

  #     - name: Testing
  #       run: flutter test

  deploy_web:
    name: Deploy Web App
    runs-on: ubuntu-20.04
    # needs: [test] 
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Create app.js file
        id: app
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: "app.js"
          encodedString: ${{ secrets.WEB_SCRIPT_JS }}

      - name: Move app.js into project
        run: |
          mv ${{ steps.app.outputs.filePath }} ./scripts/

      - name: Create .firebaserc file
        id: firebaserc
        uses: timheuer/base64-to-file@v1
        with:
          fileName: ".firebaserc"
          encodedString: ${{ secrets.FIREBASERC }}

      - name: Move .firebaserc into project
        run: |
          mv ${{ steps.firebaserc.outputs.filePath }} ./

      - name: 'Build Web App'
        run: flutter build web

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:app
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}